### ISSUE TITLE
Fork and LICENSE

### ISSUE THREAD

**Issue by pdcook** [ROUNDS-Preservation/ModdingUtils#1]
This should've been a fork, rather than just reuploading all of my code.

Additionally, my original code was released under GPLv3. By the terms of that license, you cannot re-license it under MIT. You can license it under both GPLv3 and MIT if you'd like, and in which case you need to include the GPLv3 license.

**Comment by Scyye** [comment]
1. There wasn't much of a reason to make it a fork, we were rewriting it, so to fork then just delete everything would've been redundant.
2. MIT was selected out of instinct, while I really shouldn't have selected a license, due to it being undecided among those working on this, I presume having no license would still have caused this issue to be made.
3. From one of the people helping: "We have come to the conclusion that rather than moving forward with porting this mod, we will be recreating its core functionality under a different project without reference to this one's source. This should prevent issues like this from arising "

**Comment by Scyye** [comment]
@pdcook can this be closed?

**Comment by Scyye** [comment]
No response. Closing this, and the repo.
